---
- name: MacOS Dev Workstation
  hosts: macos
  gather_facts: true
  vars_files:
    - ../vars/vars.yml
  roles:
    - role: common
      tags: [common]
    - role: homebrew
      tags: [homebrew]
    - role: dock
      tags: [dock]
    - role: shell
      tags: [shell]
    - role: tmux
      tags: [tmux]
    - role: dotfiles
      tags: [dotfiles]
