---
- name: MacOS Dev Workstation
  hosts: macos
  gather_facts: true
  vars_files:
    - ../vars/vars.yml
  roles:
    - role: homebrew
      tags: [homebrew]
    - role: dock
      tags: [dock]
    - role: shell
      tags: [shell]
    - role: tmux
      tags: [tmux]
    - role: zettlr
      tags: [zettlr]
    - role: update
      tags: [update]
    - role: tooling
      tags: [tooling]
    - role: iterm
      tags: [iterm]
